[build]
  command = "npm run build"  # Replace with your TypeScript build command
  publish = "build"  # Replace with your build output directory
  node_version = "18"  # Specify your desired Node.js version

[build.environment]
  NODE_ENV = "production"  # Set your environment variable(s) if needed


[context.production]
  publish = "build/"
  command = "node index.js"
  environment = { NODE_VERSION = "14.15.3" }
